[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Quizz 5"
name = "quizz-5"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "marimo run quizz.py"
dev = "marimo edit quizz.py"

[dependencies]
python = ">=3.13.1,<3.14"

[pypi-dependencies]
marimo = ">=0.10.9, <0.11"
